apiVersion: v1
kind: Service
metadata:
  name: flask-test-service1
spec:
  selector:
    app: flask-test-app1
  ports:
  - protocol: "TCP"
    targetPort: 80
    nodePort: 30009
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app1
spec:
  selector:
    matchLabels:
      app: flask-test-app1
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-test-app1
    spec:
      containers:
      - name: flask-test-app1
        image: abhigyanbasu/flask-webapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
